config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resources :cats
  resources :cat_rental_requests do
    post "approve", to: 'cat_rental_requests#approve'
    post "deny", to: 'cat_rental_requests#deny'
  end
  resources :users
  
  resources :sessions
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :datetime
#  end_date   :datetime
#  status     :string(255)      default("PENDING")
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :user_id, presence: true
  validates :status, inclusion: { in: ["PENDING", "APPROVED", "DENIED"] }
  validate :overlapping_approved_requests
  belongs_to(:cat)
  belongs_to(:user)
  
  def overlapping_requests
    args = [
      self.start_date.to_s, 
      self.end_date.to_s, 
      self.start_date, 
      self.end_date, 
      self.cat_id
    ]
    requests = CatRentalRequest.find_by_sql([<<-SQL, *args])
      SELECT *
      FROM cat_rental_requests
      WHERE 
      (start_date BETWEEN ? AND ?) 
        AND 
        (end_date BETWEEN ? AND ?)
        AND 
        cat_id = ?
    SQL
    requests
    
  end
  
  def overlapping_approved_requests
    requests = overlapping_requests
    if !requests.empty?
      counter = 0
      requests.each { |request| counter += 1 if request.status == "APPROVED" } 
      if counter > 1
        errors[:cat_id] << "This cat is booked for the times you chose."
      end
    end
    return
  end
  
  def overlapping_pending_requests
    requests = overlapping_requests
    requests.each { |request| request.deny! }
  end
  
  def approve!
    CatRentalRequest.transaction do
      self.status = "APPROVED"
      self.save!
      overlapping_pending_requests
    end
  end
  
  def deny!
    self.update!(status: "DENIED") if self.status == "PENDING"
  end
  
  def pending?
    self.status == "PENDING"
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  
  before_action :ensure_cat_ownership, only: [:approve, :deny]
  
  def new
    @cats = Cat.all
    @crr = CatRentalRequest.new
    render :new
  end
  
  def create
    @crr = current_user.cat_rental_requests.new(crr_params)
    
    if @crr.save
      redirect_to cat_url(@crr.cat_id)
    else
      flash.now[:errors] = @crr.errors.full_messages
      render :new
    end
  end
  
  def approve
    byebug
    @crr = CatRentalRequest.find(params[:cat_rental_request_id])
    @crr.approve!
    redirect_to cats_url
  end
  
  def deny
    @crr = CatRentalRequest.find(params[:cat_rental_request_id])
    @crr.deny!
    redirect_to cats_url
  end
  
  def crr_params
    args = [:cat_id, :start_date, :end_date, :status]
    params.require(:cat_rental_request).permit(*args)
  end
    
  def ensure_cat_ownership
    if current_user.id != params[:cat_rental_request_id].to_i
      flash.now[:errors] = "You cannot approve requests for another user's cat." ##does not work
    # @crr = CatRentalRequest.new(crr_params)
 #    @crr.errors[:user_id] << "You cannot approve requests for another user's cat."
 #    @crr.flash.now = @crr.errors[:user_id]
      redirect_to cats_url
    else
      return
    end
  end
    
  
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="POST">  
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <h>Book your kitty cat today!</h>
  
  <label for="cat">Cat!
    <select name='cat_rental_request[cat_id]'>
      <option> </option>
      <% @cats.each do |cat| %>
      <option <%= "selected" if @crr.cat_id == cat.id %> value="<%=cat.id%>">           <%="#{cat.id}"%> </option>
      <%end%>
    </select>
  </label>
  <br>
  
  <label for="start_date">Start Date
    <input type="date" name="cat_rental_request[start_date]" value="<%=@crr.start_date%>">
  </label>
  <br>
  
  <label for="end_date">End Date
    <input type="date" name="cat_rental_request[end_date]" value="<%=@crr.end_date%>">
  </label>
  <br>
  
  <input type="submit" value="Book kitty cat!!">
</form>