config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resources :cats
  resources :cat_rental_requests do
    post "approve", to: 'cat_rental_requests#approve'
    post "deny", to: 'cat_rental_requests#deny'
  end
  resources :users
  
  resources :sessions
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :datetime
#  color       :string(255)
#  name        :string(255)
#  sex         :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#

class Cat < ActiveRecord::Base
  # validates :birth_date, timeliness: { on_or_before: Date.current }
  COLORS = ['black', 'white', 'brown', 'calico', 'orange']
  SEX = ['M', 'F']
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: SEX}
  validates :name, :presence => true
  has_many(:cat_rental_requests,
  :dependent => :destroy)
  
  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  def age
    Date.current.year - birth_date.year
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  before_action :ensure_cat_ownership, only: [:edit, :update]
  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    @crr = CatRentalRequest.where(cat_id: @cat.id)
    @crr = @crr.order(:start_date)
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    # @cats = Cat.all
    
    @cat = current_user.cats.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end
  
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def ensure_cat_ownership
    errors[:user_id] << "You cannot edit another user's cat."
    flash.now = errors[:user_id]
    redirect_to cats_url if @current_user.id != params[:user_id]
  end
  
  def cat_params
    cat_attrs = [:birth_date, :color, :name, :sex, :description]
    params.require(:cat).permit(*cat_attrs)
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!" %>

<form action="<%= action_url%>" method="POST">  
  <input type="hidden" name="_method" value="<%=form_method%>">
  
  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">
  
  <h>Create a New Cat</h>
  
  <label for="name">Name
    <input 
      type="text" 
      name="cat[name]" 
      value="<%=@cat.name%>">
  </label>
  <br>
  <label for="birth_date">Birth Date
    <input 
      type="date" 
      name="cat[birth_date]" 
      value="<%=@cat.birth_date%>">
  </label>
  <br>
  
  <h3>cat gender</h3>
  <label>Male
    <input 
      type="radio" 
      name="cat[sex]" 
      value="M" 
      <%= "checked" if @cat.sex == "M" %>>
  </label>
  
  <label>Female
    <input 
      type="radio" 
      name="cat[sex]" 
      value="F" 
      <%= "checked" if @cat.sex == "F" %> >
  </label>
  <br>
    
  <label for="color">Color
    <select name='cat[color]'>
      <option> </option>
      <% Cat::COLORS.each do |color| %>
        <option 
          <%= "selected" if @cat.color == color %> 
          value="<%=color%>"> 
          <%="#{color.capitalize}"%> 
        </option>
      <%end%>
    </select>
  </label>
  <br>
  
  <label for="description">Description</label>
    <textarea id='description' name="cat[description]"><%= @cat.description %></textarea>
  
  <input type="submit" value="<%= submit_text%>">
</form>

app/views/cats/edit.html.erb
  <h>Edit Cat</h>
  
  <%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1> All Cats </h1>
<ul><% @cats.each do | cat | %> 
    <li> <%=link_to "#{cat.name}", cat_url(cat.id) %> </li>
    <% end %>  
</ul>  
<%=link_to "Create new cat", new_cat_url %>
<%=link_to "Book a cat", new_cat_rental_request_url%>

app/views/cats/new.html.erb
  <h>Create a New Cat</h>
  
  <%= render "form", cat: @cat %>  

app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>
<table>
  <tr>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Name</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td> <%=@cat.birth_date%> </td>
    <td> <%=@cat.color%> </td>
    <td> <%=@cat.name%> </td>
    <td> <%=@cat.sex%> </td>
    <td> <%=@cat.description%> </td>
  </tr>
</table>
<br>

<ol>
  <%@crr.each do |request|%>
    <li>Requestor: <%= User.find(request.user_id).username %> Start date: <%=request.start_date%>, End date: <%=request.end_date%> Request Status: <%=request.status%></li>
    <%if request.pending? && current_user.id == @cat.user_id %>
      <%=button_to "Approve", cat_rental_request_approve_url(request), method: :post%>
      <%=button_to "Deny", cat_rental_request_deny_url(request), method: :post%>
    <%end%>
  <%end%>
</ol>

<br>
<%= link_to "Cats index", cats_url %>
<%=link_to "Edit", edit_cat_url(@cat.id) %>